[workspace]
resolver = "2"
members = [
    "zino",
    "zino-cli",
    "zino-core",
    "zino-derive",
    "zino-dioxus",
    "zino-extra",
    "zino-middleware",
    "zino-model",
    "zino-router",
    "zino-rpc",
    "zino-server",
]

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
