[package]
name = "zino-model"
description = "Domain models for zino."
version = "0.32.1"
categories = ["web-programming", "database"]
keywords = ["web", "model", "orm", "schema"]
readme = "README.md"
documentation = "https://docs.rs/zino-model"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = [
    "namespace",
    "visibility",
    "tags",
    "owner-id",
    "maintainer-id",
    "edition",
]
namespace = []
visibility = []
tags = []
owner-id = []
maintainer-id = []
edition = []

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
zino-auth = { workspace = true, features = ["jwt"] }
zino-core = { workspace = true, features = ["validator-email"] }
zino-derive = { workspace = true }
zino-orm = { workspace = true }

[dependencies.strum]
version = "0.27.1"
features = ["derive"]

[lints.rust]
unsafe_code = "forbid"
unreachable_pub = "deny"
