[[endpoints]]
path = "/user/new"
method = "POST"

[endpoints.body]
schema = "newUser"

[[endpoints]]
path = "/user/{user_id}/delete"
method = "POST"

[[endpoints]]
path = "/user/{user_id}/update"
method = "POST"

[endpoints.body]
schema = "userInfo"

[[endpoints]]
path = "/user/{user_id}/view"
method = "GET"

[[endpoints]]
path = "/user/list"
method = "GET"

[endpoints.query]
roles = { type = "string", description = "User roles" }
tags = { type = "string", description = "User tags" }

[[endpoints]]
path = "/user/import"
method = "POST"

[endpoints.body]
schema = "userData"

[[endpoints]]
path = "/user/export"
method = "GET"

[endpoints.query]
format = { type = "string", enum = ["csv", "json", "jsonlines", "msgpack"], default = "json", description = "File format" }
roles = { type = "string", description = "User roles" }
tags = { type = "string", description = "User tags" }

[schemas.userId]
type = "string"
format = "uuid"
description = "User ID"

[schemas.newUser]
type = "object"
required = ["name", "roles", "account", "password"]
name = { type = "string", description = "User name" }
roles = { type = "array", items = "string", example = ["admin"], description = "User roles" }
account = { type = "string", description = "User account" }
password = { type = "string", format = "password", description = "User password" }
tags = { type = "array", items = { type = "string", format = "uuid" }, description = "User tags" }

[schemas.userInfo]
type = "object"
name = { type = "string", description = "User name" }
status = { type = "string", enum = ["Active", "Inactive", "Locked", "Deleted"], description = "User status" }
roles = { type = "string", description = "User roles" }
tags = { type = "string", description = "User tags" }

[schemas.userData]
type = "array"
items = "object"
required = ["name", "roles", "account", "password"]
name = { type = "string", description = "User name" }
roles = { type = "array", items = "string", example = ["admin"], description = "User roles" }
account = { type = "string", description = "User account" }
password = { type = "string", format = "password", description = "User password" }
tags = { type = "array", items = { type = "string", format = "uuid" }, description = "User tags" }

[models.user.visibility]
translations = [
    ["Public", "ğŸŒ"],
    ["Internal", "ğŸ”µ"],
    ["Proteched", "â›”"],
    ["Private", "ğŸ”´"],
]

[models.user.status]
translations = [
    ["Active", "ğŸ˜„"],
    ["Inactive", "ğŸ˜´"],
]

[models.user.roles]
translations = [
    ["admin", "ğŸ‘®"],
    ["worker", "ğŸ‘·"],
]

[models.user.updated_at]
translations = [
    ["$span:24h", "Updated within 1 day"],
    ["$span:7d", "Updated within 1 week"],
]
