[package]
name = "zino"
description = "Next-generation framework for composable applications in Rust."
version = "0.34.0"
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
keywords = ["http", "web", "framework"]
readme = "README.md"
documentation = "https://docs.rs/zino"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
features = [
    "auth",
    "axum",
    "i18n",
    "inertia",
    "jwt",
    "opa",
    "orm",
]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
actix = ["dep:zino-actix", "dep:zino-http", "dep:zino-openapi"]
auth = ["zino-auth", "zino-http?/auth"]
axum = ["dep:zino-axum", "dep:zino-http", "dep:zino-openapi"]
cookie = ["zino-core/cookie", "zino-http?/cookie"]
dioxus = ["zino-dioxus"]
dioxus-desktop = ["dioxus", "zino-dioxus/desktop"]
debug = ["zino-core/debug", "zino-http?/debug", "zino-openapi?/debug"]
default = ["logger"]
i18n = ["dep:zino-http", "zino-http/i18n"]
inertia = ["zino-http/inertia"]
jwt = ["auth", "zino-auth/jwt", "zino-http?/jwt"]
logger = ["zino-core/tracing-log", "zino-core/tracing-subscriber"]
metrics = ["zino-core/metrics", "zino-http?/metrics", "zino-storage/metrics"]
ntex = ["dep:zino-http", "dep:zino-ntex", "dep:zino-openapi"]
opa = ["auth", "zino-auth/opa"]
orm = [
    "zino-orm",
    "zino-actix?/orm",
    "zino-axum?/orm",
    "zino-ntex?/orm",
]
preferences = ["zino-core/preferences"]
view = ["zino-http/view"]

[dependencies]
cfg-if = { workspace = true }
serde_json = { workspace = true }
zino-auth = { workspace = true, optional = true }
zino-core = { workspace = true }
zino-http = { workspace = true, optional = true }
zino-openapi = { workspace = true, optional = true }
zino-orm = { workspace = true, optional = true }
zino-storage = { workspace = true }

[dependencies.zino-actix]
path = "../zino-actix"
version = "0.8.0"
optional = true

[dependencies.zino-axum]
path = "../zino-axum"
version = "0.8.0"
optional = true

[dependencies.zino-dioxus]
path = "../zino-dioxus"
version = "0.15.2"
optional = true

[dependencies.zino-ntex]
path = "../zino-ntex"
version = "0.8.0"
optional = true

[lints]
workspace = true
