[package]
name = "dioxus-desktop"
description = "An example for Dioxus desktop integration."
version = "0.5.2"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.5.1"
dioxus-router = "0.5.0"
tracing = "0.1.40"

[dependencies.dioxus-free-icons]
version = "0.8.6"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.zino]
path = "../../zino"
version = "0.23.3"
features = ["dioxus-desktop"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.24.3"
features = ["env-filter", "tls-native"]

[dependencies.zino-dioxus]
path = "../../zino-dioxus"
version = "0.6.6"
