[package]
name = "dioxus-app"
description = "An example for Dioxus desktop integration."
version = "0.13.0"
edition = { workspace = true }
rust-version = { workspace = true }
publish = { workspace = true }

[dependencies]
tracing = { workspace = true }
zino = { workspace = true, features = ["dioxus-desktop"] }
zino-core = { workspace = true, features = ["env-filter", "http-client", "tls-native"] }
zino-dioxus = { workspace = true }

[dependencies.dioxus]
version = "0.7.1"
features = ["desktop"]

[dependencies.dioxus-free-icons]
version = "0.10.0"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]
