# --env=prod

name = "DataCube"
version = "0.2.0"

[window]
title = "DataCube"
transparent = false

[desktop]
disable-default-menu = true
resource-dir = "public"
icon = "public/favicon.ico"
stylesheets = [
    "public/css/bulma.min.css",
    "public/css/custom.css",
]

[tracing]
filter = "warn,zino=info,zino_core=info"
