[package]
name = "dioxus-ssr"
description = "An example for Dioxus SSR integration."
version = "0.1.2"
rust-version = "1.75"
edition = "2021"
publish = false

[dependencies]
dioxus = "0.5.6"
dioxus-router = "0.5.6"
tracing = "0.1.40"

[dependencies.dioxus-free-icons]
version = "0.8.6"
features = [
    "bootstrap",
    "font-awesome-brands",
    "font-awesome-solid",
    "octicons",
]

[dependencies.zino]
path = "../../zino"
version = "0.24.2"
features = ["dioxus-ssr"]

[dependencies.zino-core]
path = "../../zino-core"
version = "0.25.2"
features = ["env-filter", "tls-native"]

[dependencies.zino-dioxus]
path = "../../zino-dioxus"
version = "0.7.2"
