[package]
name = "zino-dioxus"
description = "Dioxus components for zino."
version = "0.15.2"
categories = ["gui", "network-programming", "web-programming"]
keywords = ["zino", "dioxus", "components"]
readme = "README.md"
documentation = "https://docs.rs/zino-dioxus"
homepage = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
features = ["clipboard", "markdown"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
desktop = ["dioxus/desktop"]
clipboard = ["dioxus-sdk/clipboard"]
markdown = ["dep:comrak"]

[dependencies]
dioxus = "0.6.3"
dioxus-core = "0.6.3"
dioxus-hooks = "0.6.2"
dioxus-html = "0.6.3"
dioxus-router = "0.6.3"
chrono = { workspace = true }
rust_decimal = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
zino-core = { workspace = true, features = ["runtime-tokio"] }
zino-storage = { workspace = true }

[dependencies.comrak]
version = "0.38.0"
optional = true
default-features = false
features = ["shortcodes", "syntect"]

[dependencies.dioxus-free-icons]
version = "0.9.0"
features = ["bootstrap", "font-awesome-solid"]

[dependencies.dioxus-sdk]
version = "0.6.0"
optional = true

[dependencies.image]
version = "0.25.6"
default-features = false
features = [
    "gif",
    "ico",
    "jpeg",
    "png",
    "rayon",
]

[lints]
workspace = true
