# --env=prod

name = "data-cube"
version = "0.6.4"

[dirs]
uploads = "local/uploads"

[debug]
host = "127.0.0.1"
port = 6070

[main]
host = "127.0.0.1"
port = 6080

[[standby]]
host = "127.0.0.1"
port = 6081
tag = "portal"

[[standby]]
host = "127.0.0.1"
port = 6082
tag = "admin"

[database]
namespace = "dc"

[[mariadb]]
host = "127.0.0.1"
port = 4306
database = "data_cube"
username = "root"
password = "pOY0jO0OwsvpSu53GlJFxHlQt21naMsiIw5IMft0BEA"

[[mysql]]
host = "127.0.0.1"
port = 3306
database = "data_cube"
username = "root"
password = "pOY0jO0OwsvpSu53GlJFxHlQt21naMsiIw5IMft0BEA"

[[sqlite]]
database = "local/data/main.db"

[tracing]
filter = "warn,zino=info,zino_core=info"

[metrics]
exporter = "prometheus"
host = "127.0.0.1"
port = 9000

[openapi]
show-docs = true
rapidoc-route = "/rapidoc"
custom-html = "local/docs/rapidoc.html"
