[package]
name = "amis-app"
description = "An example for amis UI generator."
version = "0.6.1"
edition = { workspace = true }
rust-version = { workspace = true }
publish = { workspace = true }

[dependencies]
phf = "0.11.2"
zino-amis = { workspace = true }
zino-core = { workspace = true }
